### ISSUE TITLE
Setting min and max options

### ISSUE THREAD

**Issue by pushkardeshmukh1992** [icai/vue3-calendar#15]
Is there any way to disable dates using min/ max prop?

**Comment by icai** [comment]
@pushkardeshmukh1992  Don't support now!

**Comment by cybersupernova** [comment]
Still no support for startDate and endDate?

**Comment by icai** [comment]
will do this next #22

**Comment by icai** [comment]
https://github.com/icai/vue2-calendar/releases/tag/2.1.0

**Comment by cybersupernova** [comment]
Please update the documentation, don't understand how to use this feature. It would be helpful if you can setup a gist with min and max date

**Comment by icai** [comment]
@cybersupernova 
see this demo.
https://github.com/icai/vue2-calendar/blob/0e27f7d905c2e2957a280e6635ea567967e6605a/src/modules/Docs.vue#L10
