### ISSUE TITLE
v-model didn't work

### ISSUE THREAD

**Issue by aianzi** [icai/vue3-calendar#19]
when I use this component, I can just change the data-inputValue instead of props-value.
Then I got data of ''. So could you explain how to get the value? thanks a lot

**Comment by rodrigocachoeira** [comment]
You will need to change Calendar.vue of component itself, just add a watch function for inputValue, and add this.$emit('input', value), v-model should me work

**Comment by kennedyps4** [comment]
example please

**Comment by rodrigocachoeira** [comment]
In Calendar.vue

`watch: {
    currDate () {
      this.getDateRange()
    }
  },`

add inputValue watcher

`watch: {
    currDate () {
      this.getDateRange()
    },
    inputValue (value) {
        this.$emit('input', value)
    }
  },`

**Comment by icai** [comment]
based on vue  2.2.0+ https://vuejs.org/v2/guide/components.html#Customizing-Component-v-model

**Comment by icai** [comment]
updated cf830726ab858990686564ca9c0dd2ec68189729
