### ISSUE TITLE
with 'dd/MM/yyyy' format, when you select a date and open the calendar again it open the following month

### ISSUE THREAD

**Issue by ecousinet** [icai/vue3-calendar#2]
French here, when you use the dd/MM/format, if you select a day (let's say 01/12/2016) and open the calendar again to change the date it opens the next month panel with the 01/01/2017 'selected' even though the date is actually still 01/12/2016.

Took me a while to figure it out but when you instantiate date
`new Date(année, mois[, jour[, heures[, minutes[, secondes[, millisecondes]]]]]);`
Date expect month to start at 0 (0 is january, 1 february, ..., 11 december) so it can be fixed by replacing
  `date = new Date(str.substring(6, 10), str.substring(3, 5), str.substring(0, 2))`
in your parse function by
  `date = new Date(str.substring(6, 10), str.substring(3, 5) - 1, str.substring(0, 2))`

**Comment by icai** [comment]
merged
