### ISSUE TITLE
how to set it as lunar mode?

### ISSUE THREAD

**Issue by dclovec** [icai/vue3-calendar#20]
I need toggle between chinese lunar and solar.

**Comment by icai** [comment]
@dclovec I surmise your thinking. lunar is based on solar, only a map to rende the solar day, but if you to start the month day with the first day of lunar month, I have no idea.

**Comment by dclovec** [comment]
Show the lunar  to user is ok. How ? Use slot?

**Comment by dclovec** [comment]
I find it , thanks!
