### ISSUE TITLE
How to disable this calendar input?

### ISSUE THREAD

**Issue by kevinding0218** [icai/vue3-calendar#27]
Hello, thank you for providing this nice and simple component! I had one question regarding programatically enable/disable this datepicker control, is there any approach on doing that? Seems there is no property like ":disable" here...

Best,
kevin

**Comment by icai** [comment]
please see the docs 
http://blog.w3cub.com/vue2-calendar/?x-page=github#props

**Comment by kevinding0218** [comment]
Thank you for your reply! I did read the docs and tried every possible property, unfortunately I did not find the one that I need, I mean not to disable the calendar for specific date(which is using 'disabled-days-of-week')  but the entire control if possible.. would mind helping me pointing out on that?

Thank you very much for your help!
