### ISSUE TITLE
How to hide previous months?

### ISSUE THREAD

**Issue by FrancescoMussi** [icai/vue3-calendar#30]
Hello. Great component.
Just one question:

Is it possible to hide all the months (and years) previous than the current one?

**Comment by alex2wong** [comment]
or you can simply return the click handler when clicked on month previous than current one.
`@click="monthSelect(stringifyYearHeader(currDate, pan), $index)"`
or add a compute function to judge the month is visible or not.
`<template v-for="(m, $index) in text.months">
      <span :key="m" :id="m" :class="{'datepicker-dateRange-item-hidden': isHidden(m)}" ></span></template>`

**Comment by dschinnerl** [comment]
Or you can just disable days for < `minDate` || > `maxDate`...

```
<calendar
  :pane="1"
  :hasInput="false"
  :showDateOnly="true"
  :on-day-click="onDayClick"
  :format="dateFormat"
  :value="dateValue"
  :change-pane="changePane"
  :minDate="'2018-06-01'" <===
  :maxDate="'2019-06-01'" <===
>
```
