### ISSUE TITLE
Custom format not working

### ISSUE THREAD

**Issue by mtleppay** [icai/vue3-calendar#35]
Hello, when i'm trying to format date with dots. but it doesn't work.
I need 'dd.MM.yyyy' format.
Any suggestions?

**Comment by crimsonimp** [comment]
@mtleppay You can solve the problem by changing next if statement in Calendar component:

if (str.length === 10 && (this.dateFormat === 'dd-MM-yyyy' || this.dateFormat === 'dd/MM/yyyy'))

change to this

if (str.length === 10 && (this.dateFormat === 'dd.MM.yyyy' || this.dateFormat === 'dd-MM-yyyy' || this.dateFormat === 'dd/MM/yyyy'))
