### ISSUE TITLE
Incorrect display of days in the calendar

### ISSUE THREAD

**Issue by crimsonimp** [icai/vue3-calendar#38]
You have incorrectly displayed days in your calendar. Look at the first and second panes and then compare it. Can you fix it?
<img src="https://screenshotscdn.firefoxusercontent.com/images/a45f6c14-b4fc-4ca9-a639-833e4b6ee6d9.png" />

**Comment by icai** [comment]
the pic blocked @crimsonimp

**Comment by smgood** [comment]
Don't worry @crimsonimp . I found the bug on the Vue2 Calendar live demo! April 1, 2019 falls on a Monday. The Vue2 Calendar widget displays it as occurring on a Sunday.

http://blog.w3cub.com/vue2-calendar/demo/

**Comment by matuszeg** [comment]
I fixed it here https://github.com/icai/vue2-calendar/pull/41
