### ISSUE TITLE
Bug fix is not in release

### ISSUE THREAD

**Issue by LastImmort** [icai/vue3-calendar#44]
https://github.com/icai/vue2-calendar/pull/41/files is missing in the latest 2.2.4 npm package

So, old bug is still here
![image](https://user-images.githubusercontent.com/28784336/56803877-8e7e4380-682c-11e9-82d4-09c0dff07ef1.png)

**Comment by super-marrimo** [comment]
yeah, same issue. 
The pull request from @matuszeg  has been merged, but the code still not changed.
@icai

**Comment by icai** [comment]
use 2.2.5
