### ISSUE TITLE
Bootstrap styles are not applied properly

### ISSUE THREAD

**Issue by scramatte** [icai/vue3-calendar#51]
Hello,

Bootstrap styles are not applied properly.  Inside grid control must use 100% width.
Moreover I need to be able to set class of input element to handle valid/invalid feedback.

![image](https://user-images.githubusercontent.com/188766/81313137-bfbc6100-9087-11ea-821b-0ed01611cbb7.png)

Can you fix it ?

**Comment by icai** [comment]
https://www.npmjs.com/package/vue3-slot-calendar#input-slot
