### ISSUE TITLE
Add option to set first day in week

### ISSUE THREAD

**Issue by Alex-Sokolov** [icai/vue3-calendar#6]
Now it is Sunday, but I need to change to Monday

**Comment by ilia-aaron** [comment]
@Alex-Sokolov Ты решил эту проблему?

**Comment by Alex-Sokolov** [comment]
@djvonavi Да, сделал себе обёртку над плагином Flatpickr и пользуюсь теперь им 😄

**Comment by KoiLVeD** [comment]
@Alex-Sokolov в файле calendar.vue в ""let firstDayWeek = currMonthFirstDay.getDay() + 1"" убрать ""+ 1"" 

in the calendar file  ""let's firstDayWeek = currMonthFirstDay.getDay() + 1"" clean ""+ 1""

**Comment by Alex-Sokolov** [comment]
@KoiLVeD Да, можно сделать и таким образом. Но это должно быть настраиваемым

Yeah, that possible that way. But it must be configurable.

**Comment by razbakov** [comment]
@KoiLVeD @Alex-Sokolov it is not a solution, it will just move one day back
For example 01.03.2018 is Thursday, proposed change will set 01.03.2018 as Wednesday.
You also have to change `daysOfWeek` in `translations`

**Comment by mydnic** [comment]
@Alex-Sokolov no plan to support this ?

**Comment by Alex-Sokolov** [comment]
@mydnic I'm not using this plugin anymore :) and I'm not a developer

**Comment by mydnic** [comment]
@icai maybe ?

**Comment by icai** [comment]
you can pull request this issue？ @mydnic , Busy for life

**Comment by mydnic** [comment]
Appart from removing the `+ 1` I really don't know what needs to be done
