### ISSUE TITLE
Multi date selected limit 30 days

### ISSUE THREAD

**Issue by Sun-Liu** [icai/vue3-calendar#9]
Multi date selected limit 30 days
![image](https://cloud.githubusercontent.com/assets/24770162/22732161/265945c8-ee28-11e6-8453-bc10a64d4f04.png)
and Icon Font loaded out

**Comment by icai** [comment]
@Sun-Liu 
just hover status effect, I don't know what u mean
![test](https://cloud.githubusercontent.com/assets/1061012/22741113/0c4cc180-ee4d-11e6-8c00-36e64cd32f73.png)

**Comment by Sun-Liu** [comment]
I use your item, favicon.ico does not show。
![image](https://cloud.githubusercontent.com/assets/24770162/22860592/8c552654-f13d-11e6-93fc-b341d46b3810.png)
also，I can't load bootstrap-sass 
![image](https://cloud.githubusercontent.com/assets/24770162/22860612/0ccb1078-f13e-11e6-8ed1-7520d952f230.png)
Personally, I think you need to write a document to tell us how to use it

**Comment by Sun-Liu** [comment]
![image](https://cloud.githubusercontent.com/assets/24770162/22860789/1f210d72-f143-11e6-8f85-498d0dfc3ea1.png)

**Comment by Sun-Liu** [comment]
![image](https://cloud.githubusercontent.com/assets/24770162/22860801/76b3b8fa-f143-11e6-833c-011fc6fae7e9.png)

**Comment by icai** [comment]
@Sun-Liu  I use `alias` to overwrite the `bootstrap-sass` dependency, because I just use bootstrap css, but not use bootstrap javascript component.

**Comment by Sun-Liu** [comment]
Yes, but I also wrote it in your catalogue.. But I don't know why this kind of thing happens
